---
sidebar: sidebar 
permalink: task-manage-billing-preferences.html 
keywords: billing, configure, license, licensing, licenses, subscriptions, marketplace, keystone, cvo 
summary: NetApp Consoleで課金設定を構成して、ライセンス、マーケットプレイス サブスクリプション、およびKeystone契約の課金および更新方法を制御します。 
---
= 請求設定を管理する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Consoleで課金設定を構成して管理し、組織のアカウントに容量使用量、更新、請求書を適用する方法を制御できます。課金設定により、使用料がNetAppライセンス、クラウド マーケットプレイス契約、またはKeystone契約のいずれから発生するかが決まります。

.開始する前に
* *請求管理者*または*組織管理者*の役割を持っています。
* 関連するすべてのマーケットプレイス サブスクリプションが組織にリンクされます。
* *Licenses and subscriptions* の既存の構成を確認しました。




== 請求設定を行う

コンソールが課金ソース全体に使用料金を適用する方法を選択できます。これにより、どのアカウントに最初に請求されるか、および更新がどのように処理されるかが決まります。

.手順
. NetApp Consoleで、*ガバナンス >Licenses and subscriptions*を選択します。
. *請求設定*を選択します。
. 次のいずれかの課金モードを選択します。
+
** * 最初にNetAppライセンスを使用* – 最初にNetAppライセンスを使用し、その後、追加の使用にはマーケットプレイス サブスクリプションを使用します。
** *マーケットプレイス サブスクリプションのみ* – すべての使用量をマーケットプレイス サブスクリプションを通じて直接請求します。


. *Marketplace サブスクリプション* で、各ハイパースケーラー (AWS、Azure、Google Cloud) のサブスクリプションを選択します。
. 単一のハイパースケーラーで複数のサブスクリプションを使用する場合は、*カスタム CVO 構成* を有効にします。
. (オプション) *請求書連絡先*と*通知連絡先*を更新します。
. (オプション) 請求を内部会計コードに関連付けるには、*コスト センター タグ* を入力します。
. *変更を保存*を選択します。
. プロンプトが表示されたら、確認ダイアログを確認し、「確認」を選択します。


.結果
NetApp Consoleは課金マッピングを更新します。今後のサービス料金と更新では、選択した構成が使用されます。


NOTE: 課金モードを変更すると、サービス料金の適用方法が再分配されます。新しいCloud Volumes ONTAP (CVO) インスタンスは、選択した構成を自動的に継承します。



== カスタムCVO構成を有効にする

カスタム CVO 構成を使用すると、同じハイパースケーラーで複数のマーケットプレイス サブスクリプションを割り当てることができます。組織が個別のビジネス ユニットまたは環境ごとに異なる請求アカウントを管理している場合は、このモードを使用します。

.手順
. NetApp Consoleで、*ガバナンス >Licenses and subscriptions*を選択します。
. *請求設定*を選択します。
. **Marketplace サブスクリプション** で、*カスタム CVO 構成* を有効にします。
. **変更を保存**を選択します。


.結果
同じハイパースケーラーの下にある個々のCloud Volumes ONTAPインスタンスに特定のマーケットプレイス サブスクリプションを割り当てることができるようになりました。


WARNING: これを有効にすると、**課金設定** タブからカスタム CVO 構成を元に戻すことはできません。無効にすると、すべての CVO 課金がデータ サービスの標準課金構成にリセットされます。



== マーケットプレイスの設定を編集する

マーケットプレイスの構成詳細を編集して、サブスクリプションをクラウド プロジェクトに関連付けたり、契約情報を更新したりできます。

.手順
. *Licenses and subscriptions*を開きます。
. *請求設定*を選択します。
. 次のビューを選択します。
+
** *マーケットプレイスのサブスクリプション名*
** *クラウド プロジェクト* (Google Cloud のみ)
** *サブスクリプションタイプ* (年間またはPAYGO)


. *変更を保存*を選択します。


.結果
新しい構成はすぐに有効になり、課金データがクラウド プロバイダーと同期されます。


TIP: 1 つのサブスクリプションを複数のクラウド プロジェクトにマップするには、まず *カスタム CVO 構成* が有効になっていることを確認します。



== 請求の変更を確認または元に戻す

請求設定を更新するたびに、誤って変更されないように確認が必要になります。

.変更を確認する
. 請求設定を編集した後、「*変更を保存*」を選択します。
. 確認ダイアログで概要を確認します。
. 更新を適用するには「*保存*」を選択し、更新を破棄するには「*キャンセル*」を選択します。


.標準請求に戻す
. *課金設定*を開きます。
. *カスタム CVO 構成* を無効にします。
. プロンプトが表示されたら、標準構成に戻すことを確認します。


.結果
CVO インスタンスは、他のデータ サービスに使用されるデフォルトの標準課金方法に戻ります。
