---
sidebar: sidebar 
permalink: task-manage-private-google-cloud.html 
keywords: activate, license, licensing, install, request capacity, link subscription, keystone flex, bluexp, netapp console, marketplace, google cloud 
summary: Google Cloud コンソールのNetApp Consoleリストに対する Marketplace のプライベート オファーを承認します。コンソールで Google Cloud 認証情報を設定します。 
---
= NetApp Consoleの Google Cloud プライベート オファーを承認して構成する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Google Cloud コンソールのNetApp Consoleリストに対する Marketplace のプライベート オファーを承認します。コンソールで Google Cloud 認証情報を設定します。

.開始する前に
* NetApp の営業担当者と協力してプライベート オファーを作成します。営業チームがオファー リンクを提供する必要があります。
* 請求先アカウントは無料トライアル中であってはなりません。無料トライアルアカウントではプライベートオファーを受け入れることはできません。試用版の請求アカウントを使用しようとすると、エラーが発生し、 NetAppクラウド チームからのサポートが必要になります。
* オファーを承諾するには、次の Google Cloud 権限が必要です。
+
** `roles/billing.admin`対象となる Cloud Billing アカウントまたは Google Cloud 組織向け
** `roles/viewer`Cloud Billing アカウントに請求されるプロジェクトの






== Google Cloud でプライベート オファーを承諾する

Google Cloud プロジェクトは、1 つの Marketplace サブスクリプションにのみ関連付けることができます。同じ Google Cloud プロジェクト内のワークロードに 2 つの異なるサブスクリプションを使用する場合は、サブスクリプションごとに 1 つずつ、2 つの個別のコンソール アカウントを作成する必要があります。

[IMPORTANT]
====
プライベートオファーを有効にするには、すべての手順を完了する必要があります。手順を省略すると、二重請求などの問題が発生する可能性があります。

オファーの条件、価格、詳細に矛盾が見られる場合、またはどのオファーを受け入れるべきかわからない場合は、オファーを受け入れないでください。詳細については、 NetAppアカウント チームにお問い合わせください。

====
[NOTE]
====
すでにアクティブな PAYGO サブスクリプションまたは修正されたプライベート オファーがある場合は、承認手順を実行するだけで済みます。このような場合、マーケットプレイスは同じリスト内のプランを更新し、同じサブスクリプション ID を保持するため、コンソールのサブスクリプションの関連付けはそのまま維持されます。

====
.手順
. NetApp 営業チームから提供されたプライベートオファーの有効化リンクを選択してください。リンクは以下のようになります：
`https://console.cloud.google.com/marketplace/private-offers/aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeee`
. Google Cloud Marketplace にリダイレクトされ、オファーの詳細を確認できます。
+
.. **請求先アカウント**
.. **製品**: NetApp Console
.. **オファーの詳細**
.. **価格**
+
[NOTE]
====
プランの詳細、期間、価格を慎重に確認してください。何か誤りがある場合は、オファーを受け入れないでください。修正については、 NetAppアカウント チームにお問い合わせください。

====


. 情報が正確であることを確認し、利用規約に同意して、* * Accept * * を選択します。
. サブスクリプションの作成中は、読み込みアイコンが表示されます。
. サブスクリプションが正常に作成されると、ポップアップ ウィンドウが表示されます: *注文リクエストがNetApp, Inc. に送信されました。*
. **REGISTER WITH NETAPP, Inc.**を選択します。NetApp Consoleにリダイレクトされ、サブスクリプションの設定を完了します。プライベートオファーが組織内の別のユーザによって承認された場合：
+
.. Google Cloud Marketplace で、[**注文**] に移動します。
.. ステータスが **保留中** のオファーを見つけます。
.. 3点メニューを選択し、**NetApp、Inc.に登録**を選択します。


. リダイレクトされます `https://console.netapp.com`サインインを求められます。
. ログイン後、次のページにリダイレクトされます。 `https://console.netapp.com/licenses/overview` 。次の操作を行う必要があるポップアップが表示されます。
+
.. *SaaS マーケットプレイス サブスクリプション* の表示名を入力します。
.. サブスクリプションへのアクセス権を付与する Console *Organizations* を選択してください。
.. オプションとして、1 つの Console 組織内の既存の Marketplace サブスクリプションを自動的に置き換える場合は、**既存のサブスクリプションを置き換える**を有効にすることができます。
+
[NOTE]
====
*** この置換オプションは、単一のコンソール アカウントに制限されます。
*** 複数のコンソール アカウントを同じ Marketplace サブスクリプションに関連付ける必要がある場合は、追加のアカウントを手動で構成する必要があります。


====


. **Associate** を選択します。
. フォームに必要事項を入力して、サブスクリプションをコンソール組織に関連付けます。**Associate** を選択します。
. サブスクリプションを関連付けた後、**請求設定**タブを選択してください。
. マーケットプレイスのサブスクリプション オプションを確認します。
. 請求するマーケットプレイスのサブスクリプションを選択します。これは、オプションが複数ある場合にのみ適用されます。
. **変更を保存**を選択します。
. 複数のクラウド プロバイダにまたがる複数のサブスクリプションがある場合は、必要に応じてこれらの手順を繰り返してください。


マーケットプレイスサブスクリプションと直接ライセンスの請求の詳細については、 link:https://docs.netapp.com/us-en/console-licenses-subscriptions/concept-billing-preferences.html["請求設定に関するドキュメント"]。
