---
sidebar: sidebar 
permalink: task-manage-private-azure.html 
keywords: activate, license, licensing, install, request capacity, link subscription, keystone flex, bluexp, netapp console, marketplace, azure 
summary: AWS、Azure、Google Cloud 向けの、一般的な、ハイパースケーラー固有の、エンドツーエンドのプライベート オファー プロセスと、 NetAppインテリジェント サービスの承認およびアクティベーション ガイドを管理します。 
---
= NetAppコンソールの Azure プライベート オファーを承認してアクティブ化する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Azure ポータルで、 NetAppコンソールの Marketplace プライベート オファーを承諾してサブスクライブします。コンソールで Azure 資格情報を構成します。

.開始する前に
* NetApp の営業担当者と協力して、Azure 請求 ID のプライベート オファーを作成します。
* Azure Marketplace でプライベート オファーを受け入れるために必要なアクセス許可があります。
+
** エンタープライズ契約 (EA): *エンタープライズ管理者*
** Microsoft 顧客契約 (MCA): *請求先アカウント所有者* または *請求先アカウント共同作成者*


* Azure Marketplace でプライベート オファーを購入し、サブスクリプションを作成するには、必要なアクセス許可が必要です。
+
** 使用されている Azure サブスクリプションの *サブスクリプション所有者* または *サブスクリプション共同作成者*


* 必要な権限を持っている場合、個人がプライベートオファーを承諾して購入することもできます。




== Azure ポータルでプライベート オファーを承認してサブスクライブする

Azure サブスクリプションは、1 つの Marketplace サブスクリプションにのみ関連付けることができます。同じ Azure サブスクリプション内のワークロードに 2 つの異なる Marketplace サブスクリプションを使用する場合は、サブスクリプションごとに 1 つずつ、2 つの個別のコンソール アカウントを作成する必要があります。複数のCloud Volumes ONTAPインスタンスがあり、異なるサブスクリプション間で課金を分割する場合は、サブスクリプションごとに個別のコンソール アカウントを作成します。

[IMPORTANT]
====
プライベートオファーを承諾して有効にするには、すべての手順を完了する必要があります。手順を省略すると、アクティベーションの問題が発生したり、二重充電が発生したりする可能性があります。

オファーの条件、価格、詳細に矛盾が見られる場合、またはどのオファーを受け入れるべきかわからない場合は、オファーを受け入れないでください。NetAppの営業チームにお問い合わせください。

オファーを複数回承諾して有効化すると、二重に請求されます。

====
.手順
. NetAppの営業チームから提供されたプライベート オファー リンクをクリックしてサインインします。リンクが利用できない場合は、Azure ポータルに直接サインインします。
. Azure サービスから *Marketplace* を検索または選択します。
. マーケットプレイス ページで、*管理* セクションの *プライベート オファー管理* をクリックします。
. プライベートオファーの詳細を確認するには、[表示 + 承認]* をクリックします。
+
.. *プランの詳細*、*期間*、*価格*が正しいことを確認します。
.. 詳細が正しくない場合は、登録しないでください。オファーを修正するには、 NetAppの営業チームにお問い合わせください。


. 確認して、「プライベートオファーを承諾」をクリックします。
. *購入*をクリックして購入プロセスを完了します。
+
[NOTE]
====
*購入*ボタンが利用できない場合は、必要な購入権限があることを確認してください。そうでない場合は、購入ウィンドウのリンクをコピーして、組織内の承認されたユーザーと共有してください。

====
. 購入ワークフローでは、次のようになります。
+
.. 使用する*Azure サブスクリプション*を選択します。
.. サブスクリプションが作成される*リソース グループ*を選択します。
.. 新しいサブスクリプションの*名前*を入力します。


. 必要に応じて、*タグ* (製品、サイトの場所、ワークロード定義、または命名規則) を設定します。
. *確認して登録*をクリックし、詳細を確認してから*登録*をクリックします。
. サブスクリプションが正常に作成されたら、「*今すぐアカウントを構成*」をクリックします。これにより、 NetAppコンソールにリダイレクトされ、構成が完了します。
+
[NOTE]
====
Azure 側の自動化は完了するまでに 30 秒から 5 分かかる場合があります。*今すぐアカウントを構成する* をクリックする前にページが閉じられていた場合は、Azure ポータルのサービスに戻ります。サブスクリプションは「*保留中の構成*」として表示されます。選択して設定を続行します。

====
. リダイレクトされます https://console.netapp.com[]サインインを求められます。
. ログイン後、次のページにリダイレクトされます。 https://console.netapp.com/licenses/overview[] 。次のプロンプトが表示されます:
+
.. マーケットプレイス サブスクリプションの *表示名* を入力します。
.. このサブスクリプションにアクセスできるコンソール *アカウント* を選択します。
.. オプションで、*既存のサブスクリプションの置き換え* を有効にして、1 つのコンソール アカウント内の既存のマーケットプレイス サブスクリプションを自動的に置き換えることができます。
+
[NOTE]
====
*** この置換オプションは、単一のコンソール アカウントに制限されます。
*** 複数のコンソール アカウントを同じマーケットプレイス サブスクリプションに関連付けるには、追加のアカウントを手動で構成します。


====


. *関連付け*をクリックし、*完了*をクリックします。


[IMPORTANT]
====
購入を有効にして割引価格を適用するには、コンソールでサブスクリプションの割り当てを完了する必要があります。

====


== Azure 資格情報を使用してサブスクリプションを構成する

. コンソールで、*ガバナンス > ライセンスとサブスクリプション* に移動し、*マーケットプレイス サブスクリプション* タブを選択します。
. サブスクリプションの詳細を検証します。
+
.. 作成したマーケットプレイスサブスクリプションを見つけます。
.. 行を展開して詳細を確認し、サブスクリプションがコンソール アカウントに関連付けられていることを確認します。


. サブスクリプションの横にある*3つのドットのメニュー*をクリックし、*構成*を選択します。
. 適切な*Azure サブスクリプション*を選択し、*構成*をクリックします。


この Azure 資格情報に対する Marketplace 料金は、Marketplace サブスクリプションを通じて請求されるようになりました。年間契約の場合、この資格情報の使用は年間契約にカウントされます。

[IMPORTANT]
====
サブスクリプションに関連付けるコンソール アカウントの各 Azure 資格情報に対して、手順 1 ～ 4 を繰り返します。

* 別のコンソール組織の資格情報を関連付けるには、[*組織*] ドロップダウンを使用して組織を切り替え、手順を繰り返します。
* 別のエージェントの資格情報を関連付けるには、[*エージェント*] ドロップダウンを使用して切り替え、手順を繰り返します。


====