---
sidebar: sidebar 
permalink: task-homepage.html 
keywords: license, licensing, dashboard, capacity license, capacity based license, add license, install license, bluexp, netapp console, cloud volumes ontap license, cloud volumes ontap 
summary: コンソールの概要ダッシュボードで、組織のすべてのサブスクリプションとライセンスの概要を確認します。 
---
= ダッシュボードの概要を使用する
:allow-uri-read: 




== ダッシュボードの概要を使用する

[role="lead"]
コンソールの*概要*ダッシュボードを使用して、ライセンスとサブスクリプションの健全性を監視し、サブスクリプションの有効期限や容量制限に達したときにコストを管理してサービスを維持できるようにします。

各データ サービス ( Cloud Volumes ONTAPを含む) に関する特定のライセンスとサブスクリプションの情報を表示し、それぞれの詳細にドリルダウンできます。

また、容量制限や有効期限が近づいていることも通知され、対応が求められます。



=== 特定のデータ サービスの詳細を表示する

*概要*ダッシュボードでは、次のデータ サービスの詳細を表示できます。

* Cloud Volumes ONTAP
* ディザスタ リカバリ
* ランサムウェア耐性
* バックアップとリカバリ
* クラウド階層化


たとえば、 Cloud Volumes ONTAPリソースの管理を担当する管理者は、各ライセンスまたはサブスクリプションの現在の容量を表示できるため、自分の権限内のリソースを重点的に把握できます。


NOTE: ダッシュボードからライセンスを更新したり削除したりすることはできますが、新しいライセンスやサブスクリプションを追加することはできません。

link:task-manage-data-services-licenses.html["ライセンスの管理について詳しくはこちら"^] 。link:task-manage-subscriptions.html["サブスクリプションの管理について詳しくはこちら"^] 。

.手順
. NetApp Consoleメニューから、*ガバナンス >Licenses and subscriptions*を選択します。
. *概要*を選択します。
. 各データ サービス ( Cloud Volumes ONTAPを含む) の [*表示*] を選択して、詳細を表示し、ライセンスとサブスクリプションを管理します。
+
各タイルには、容量の概要がグラフィカルに表示されます。詳細ページを表示して、その容量の支払い方法を確認し、管理することができます。

. *ライセンス* または *サブスクリプション* タブを選択します。
. 列フィルターとフィルターする値を選択して、テーブルをフィルターします。たとえば、[*サブスクリプション*] タブでは、[タイプ] 列を年間契約またはサブスクリプションでフィルタリングできます。
. 表に表示される列をカスタマイズします。  *列*アイコンを選択して表示または非表示にする列を指定することにより、テーブルに列を追加したり削除したりできます。
. 任意の行を展開すると、サブスクリプションまたはライセンスに含まれる内容、購入した容量、条件の詳細が表示されます。
. アクション メニューを使用して、ライセンスの更新やサブスクリプションの別の組織への関連付けなど、特定のライセンスまたはサブスクリプションを管理します。
+
特定のサービスの*概要*ページから新しいライセンスまたはサブスクリプションを追加することはできません。ライセンスまたはサブスクリプションは、それぞれ *直接ライセンス* タブまたは *マーケットプレイス サブスクリプション* タブからのみ追加できます。

+
link:task-data-services-licenses.html["ライセンスの管理について詳しくはこちらをご覧ください。"] link:task-manage-subscriptions.html["サブスクリプションの管理について詳しくはこちらをご覧ください。"]





=== ライセンスまたはサブスクリプションの問題を解決する

解決する必要があるライセンスとサブスクリプションの問題を表示できます。問題には、期限切れまたは容量に達したライセンスとサブスクリプションが含まれます。

. NetApp Consoleメニューから、*ガバナンス >Licenses and subscriptions*を選択します。
. *概要*を選択します。
. 調整が必要な問題を表示するには、[*アクションが必要*] タイルで [*解決*] を選択します。  *解決* が表示されない場合は、現時点で対処が必要な問題はありません。
. *アクションが必要* ページで、*ライセンス* タブまたは *サブスクリプション* タブを選択します。
. アクション メニューを使用して問題を解決します。
+
link:task-manage-data-services-licenses.html["ライセンスの管理について詳しくはこちら"^] 。link:task-manage-subscriptions.html["サブスクリプションの管理について詳しくはこちら"^] 。


