---
sidebar: sidebar 
permalink: task-homepage.html 
keywords: license, licensing, dashboard, capacity license, capacity based license, add license, install license, bluexp, netapp console, cloud volumes ontap license, cloud volumes ontap 
summary: コンソールの概要ダッシュボードで、組織のすべてのサブスクリプションとライセンスの概要を確認します。 
---
= ダッシュボードの概要を使用する
:allow-uri-read: 




== ダッシュボードの概要を使用する

[role="lead"]
NetApp コンソールの*概要*ダッシュボードを使用すると、ライセンスとサブスクリプションのステータスを監視し、サブスクリプションの有効期限や容量制限に達した場合でも、コストを管理し、サービスを維持できます。

各データサービス（Cloud Volumes ONTAP を含む）に関する特定のライセンスおよびサブスクリプション情報を表示できます。

Licenses and subscriptionsダッシュボードは、間近に迫った容量制限や有効期限切れを警告し、必要な措置を講じるよう促します。



=== 特定のデータ サービスの詳細を表示する

*Overview* ダッシュボードには、以下のサービスに関する詳細情報が表示されます：

* バックアップとリカバリ
* クラウド階層化
* Cloud Volumes ONTAP
* ディザスタ リカバリ
* ランサムウェア耐性


たとえば、 Cloud Volumes ONTAPリソースの管理を担当する管理者は、各ライセンスまたはサブスクリプションの現在の容量を表示できるため、自分の権限内のリソースを重点的に把握できます。


NOTE: ダッシュボードからライセンスを更新したり削除したりすることはできますが、新しいライセンスやサブスクリプションを追加することはできません。

link:task-manage-data-services-licenses.html["ライセンスの管理について詳しくはこちら"]。link:task-manage-subscriptions.html["サブスクリプションの管理について詳しくはこちら"]。

.手順
. NetApp Consoleメニューから、*管理 >Licenses and subscriptions*を選択します。
. *概要*を選択します。
. 各データ サービス ( Cloud Volumes ONTAPを含む) の [*表示*] を選択して、詳細を表示し、ライセンスとサブスクリプションを管理します。
+
各タイルには、容量の概要がグラフィカルに表示されます。詳細ページを表示して、その容量の支払い方法を確認し、管理することができます。

. *ライセンス* または *サブスクリプション* タブを選択します。
. 列フィルターとフィルターする値を選択して、テーブルをフィルターします。たとえば、[*サブスクリプション*] タブでは、[タイプ] 列を年間契約またはサブスクリプションでフィルタリングできます。
. 表に表示される列をカスタマイズします。*列*アイコンを選択して表示または非表示にする列を指定することにより、テーブルに列を追加したり削除したりできます。
. 任意の行を展開すると、サブスクリプションまたはライセンスに含まれる内容、購入した容量、条件の詳細が表示されます。
. アクション メニューを使用して、ライセンスの更新やサブスクリプションの別の組織への関連付けなど、特定のライセンスまたはサブスクリプションを管理します。
+
特定のサービスについて、*概要*ページから新しいライセンスやサブスクリプションを追加することはできません。ライセンスは*直接ライセンス*タブからのみ追加でき、サブスクリプションは*マーケットプレイスサブスクリプション*タブからのみ追加できます。

+
link:task-manage-data-services-licenses.html["ライセンスの管理について詳しくはこちらをご覧ください。"] link:task-manage-subscriptions.html["サブスクリプションの管理について詳しくはこちらをご覧ください。"]





=== ライセンスまたはサブスクリプションの問題を解決する

概要ダッシュボードでは、解決が必要なライセンスおよびサブスクリプションの問題を確認できます。問題には、有効期限が切れるライセンスとサブスクリプション、または容量に達しているライセンスとサブスクリプションが含まれます。

. NetApp Consoleメニューから、*管理 >Licenses and subscriptions*を選択します。
. *概要*を選択します。
. *Requires action*タイルで*Resolve*を選択すると、調整が必要な問題が表示されます。*Resolve*が表示されない場合は、対処が必要な問題はありません。
. *アクションが必要* ページで、*ライセンス* タブまたは *サブスクリプション* タブを選択します。
. アクション メニューを使用して問題を解決します。
+
link:task-manage-data-services-licenses.html["ライセンスの管理について詳しくはこちら"]。link:task-manage-subscriptions.html["サブスクリプションの管理について詳しくはこちら"]。


