---
sidebar: sidebar 
permalink: task-manage-private-aws.html 
keywords: activate, license, licensing, install, request capacity, link subscription, keystone flex, bluexp, netapp console, marketplace, aws 
summary: AWS、Azure、Google Cloud 向けの、一般的な、ハイパースケーラー固有の、エンドツーエンドのプライベート オファー プロセスと、 NetAppインテリジェント サービスの承認およびアクティベーション ガイドを管理します。 
---
= NetApp Consoleの AWS Marketplace プライベートオファーを承認して設定する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
AWS コンソールでNetApp Consoleの Marketplace プライベートオファーを受け入れ、コンソールで AWS 認証情報を設定します。

.開始する前に
* NetApp の営業担当者と協力してプライベート オファーを作成し、アクティベーション リンクを取得します。
* 必要な AWS Marketplace 権限があることを確認します。
+
** link:https://docs.aws.amazon.com/marketplace/latest/buyerguide/buyer-private-offers-subscribing.html["プライベートオファーの表示と購読"]
** link:https://docs.aws.amazon.com/marketplace/latest/buyerguide/buyer-iam-users-groups-policies.html["購入者の権限の検証"]






== AWSコンソールでプライベートオファーを承認する

購入を有効にして割引価格を適用するには、コンソールでサブスクリプションの割り当てを完了する必要があります。

[NOTE]
====
プライベートオファーを有効にするには、すべての手順を完了する必要があります。手順を省略すると請求エラーが発生する可能性があります。オファーを複数回承諾して有効化すると、二重に請求されます。

====
.手順
. NetAppセールス チームからのプライベート オファーのアクティベーション リンクをクリックします。リンクは次のようになります。
`https://aws.amazon.com/marketplace/saas/ordering?productId=aaa&offerId=offer-aaa`
+
 If you did not receive the link, view private offers in the AWS Marketplace console. The following permissions are required:
+
** AWS 管理ポリシーを使用する: *AWSMarketplaceRead-only*、*AWSMarketplaceManageSubscriptions*、または *AWSMarketplaceFullAccess*
** カスタム IAM ポリシーの使用: `aws-marketplace:ListPrivateListings`そして `aws-marketplace:ViewSubscriptions`


. プライベートオファーを表示するために AWS Marketplace にリダイレクトされます。
+
[NOTE]
====
プライベートオファーは公開リストの上に作成されます。*オファーの選択*ドロップダウンを使用して、公開オファーと非公開オファーを切り替えます。

====
. プライベートオファーの詳細を確認し、契約内容と一致していることを確認します。間違っている場合は受け入れないでください。NetAppアカウント チームにお問い合わせください。
+
[NOTE]
====
プライベートオファーには次の 2 つの種類があります。

** *オンデマンド利用*
+
*** 価格情報
*** 法的用語


** *契約*
+
*** 期間と日付
*** 更新設定
*** 契約オプション
*** 契約合計金額




契約オファーの場合は、合意したユニット数を入力します。Cloud Volumes ONTAPの場合は、サブスクライブする前に正しいライセンスを選択してください。

====
. プライベートオファーを承諾するには、次の手順を実行します。
+
.. オンデマンドで使用する場合は、「*サブスクライブ*」をクリックします。
.. 契約オファーの場合は、各サービスのユニット数を入力し、「契約を作成」をクリックします。


. 承認されると、バナーでサブスクリプションが確認され、登録手順が示されます。
. *アカウントを設定*をクリックします。これにより、サブスクリプションを構成するためにNetApp Consoleにリダイレクトされます。
+
[NOTE]
====
オファーを承諾したが登録を完了していない場合は、製品ページに戻ります。契約リストの場合は、「*購入オプションを表示*」をクリックしてオファーを表示し、「*アカウントを設定*」を選択します。

====
. Sign in https://console.netapp.com[]コンソールアカウントを使用します。
. ログイン後、 https://console.netapp.com/licenses/overview[] 。次のプロンプトが表示されます:
+
.. マーケットプレイス サブスクリプションの *表示名* を入力します。
.. サブスクリプションにアクセスできるコンソール *アカウント* を選択します。
.. [オプション] *既存のサブスクリプションの置き換え* を有効にして、1 つのアカウントの既存のサブスクリプションを上書きします。
+
[NOTE]
====
*** 交換は 1 つのコンソール アカウントにのみ適用されます。
*** 複数のアカウントを同じサブスクリプションに関連付けるには、追加のアカウントを手動で構成します。
*** 資格情報がサブスクリプションに関連付けられていない場合は、次のセクションの説明に従って手動で関連付けます。


====


. **関連付け**をクリックします。
. フォームに入力して、サブスクリプションをコンソール組織に関連付けます。次に、[**関連付け**] をクリックします。
. サブスクリプションを関連付けた後、[**課金設定**] タブに移動して選択します。
. マーケットプレイスのサブスクリプション オプションを確認します。
. 請求するマーケットプレイスのサブスクリプションを選択します。これは、オプションが複数ある場合にのみ適用されます。
. **変更を保存**を選択します。
. 複数のハイパースケーラーに複数のサブスクリプションがある場合は、必要に応じてこれらの手順を繰り返します。


マーケットプレイスサブスクリプションと直接ライセンスの請求の詳細については、link:https://docs.netapp.com/us-en/console-licenses-subscriptions/concept-billing-preferences.html["請求設定に関するドキュメント"] 。
